version: "3.9"

services:
  database: 
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
    network_mode: "host"
volumes:
  pgdata:
    driver: local 